language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-resp-flatfile' ]; then cd .. && eval "mv $currentfolder generator-resp-flatfile" && cd generator-resp-flatfile; fi

